import pickle
from . import models

'''
reference : pickle of list(model architechture, weight) generated by predict.
'''

def predict(args):
    print(args)

    print(args.input)
    print(args.reference)

    model = models.MEnet()