import pickle
import MEnet

'''
reference : pickle of list(model architechture, weight) generated by predict.
'''

def predict(args):
    print(args)

    print(args.input)
    print(args.model)

    with open(args.model, mode='rb') as f:
        model_params = pickle.load(f)

    # print(model_params)
    model = MEnet.MEnet(model_params[0])
    model.load_state_dict(model_params[1])
    model = model.to(device)

    model